spring.profiles.active=local
spring.application.name=smartboarding-api

spring.datasource.url=jdbc:postgresql://localhost:5433/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

api.security.token.secret=${JWT_SECRET}
auth.pepper=${AUTH_PEPPER}

firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:}

# Logging — suprimir ruídos de inicialização
logging.level.org.hibernate.orm.core=WARN
logging.level.org.springframework.boot.devtools=WARN
logging.level.org.springframework.security=WARN
